fix(diag): add missing png backend for graphviz
Add missing dependencies to enable png backend for the graphviz. This is
not an ideal solution, but the way it is configured now:

- glib (transitive dependency pulled by pango) enables sysprof by
  default, it's meson configuration has a on/off option, but it is not
  exposed in the conan package
- there is no sysprof package for conan, so the fix uses hack with
  absolute path hardcoded for the sysprof.
- PNG should be made into the optional target, but it will come later,
  when I'm working on fine-tuning the wrapped packages and trimming
  unnecessary dependencies, right now getting the tests working has
  a higher priority.

Errors for future reference: the first error, triggered during the
glib build.

```log
/usr/bin/ld: /home/haxscramper/.conan2/p/b/glib95a6b1a4417c3/b/build-release/gio/libgio-2.0.a(gtask.c.o): in function `g_task_class_intern_init':
gtask.c:(.text+0x2605): undefined reference to `g_trace_define_int64_counter'
/usr/bin/ld: gtask.c:(.text+0x2621): undefined reference to `g_trace_define_int64_counter'
/usr/bin/ld: /home/haxscramper/.conan2/p/b/glib95a6b1a4417c3/b/build-release/gio/libgio-2.0.a(gtask.c.o): in function `g_task_thread_pool_thread':
gtask.c:(.text+0x295b): undefined reference to `g_trace_set_int64_counter'
/usr/bin/ld: gtask.c:(.text+0x2a5d): undefined reference to `g_trace_set_int64_counter'
/usr/bin/ld: gtask.c:(.text+0x2aef): undefined reference to `g_trace_set_int64_counter'
/usr/bin/ld: /home/haxscramper/.conan2/p/b/glib95a6b1a4417c3/b/build-release/gio/libgio-2.0.a(gtask.c.o): in function `task_pool_manager_timeout':
gtask.c:(.text+0x2c07): undefined reference to `g_trace_set_int64_counter'
```

This is the second error, triggered because something in the glib uses
sysprof.

```log
[408/411] Linking CXX shared library plugin/neato_layout/libgvplugin_neato_layout.so.8.0.12
[409/411] Creating library symlink plugin/neato_layout/libgvplugin_neato_layout.so.8 plugin/neato_layout/libgvplugin_neato_layout.so
[410/411] Linking CXX executable cmd/dot/dot_builtins
FAILED: [code=1] cmd/dot/dot_builtins
/usr/bin/ld: plugin/pango/libgvplugin_pango.so.8.0.12: undefined reference to `sysprof_clock'
/usr/bin/ld: plugin/pango/libgvplugin_pango.so.8.0.12: undefined reference to `sysprof_collector_request_counters'
/usr/bin/ld: plugin/pango/libgvplugin_pango.so.8.0.12: undefined reference to `sysprof_collector_mark_vprintf'
/usr/bin/ld: plugin/pango/libgvplugin_pango.so.8.0.12: undefined reference to `sysprof_collector_define_counters'
/usr/bin/ld: plugin/pango/libgvplugin_pango.so.8.0.12: undefined reference to `sysprof_collector_set_counters'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
[411/411] Linking CXX executable cmd/tools/gvpack
```